import React, { useEffect, useRef } from 'react'
import analytics from '../analytics/analytics.js'
import { smoothScrollTo } from '../utils/scroll.js'

export default function Article() {
  const p1Ref = useRef(null)
  const p2Ref = useRef(null)
  const p3Ref = useRef(null)
  const p4Ref = useRef(null)

  useEffect(() => {
    const seen = new Set()
    const io = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        const id = entry.target.getAttribute('data-id')
        if (entry.isIntersecting) {
          analytics.markSectionOpen(id)
          if (!seen.has(id)) {
            analytics.trackSectionOpen(id)
            seen.add(id)
          }
        } else {
          analytics.markSectionClose(id)
        }
      })
    }, { threshold: 0.6 })

    const els = [p1Ref.current, p2Ref.current, p3Ref.current, p4Ref.current].filter(Boolean)
    els.forEach(el => io.observe(el))
    return () => {
      els.forEach(el => io.unobserve(el))
      io.disconnect()
    }
  }, [])

  const goNext = (ref) => {
    if (ref?.current && ref.current.scrollIntoView) {
      ref.current.scrollIntoView({ behavior: 'smooth', block: 'start' })
    } else if (ref?.current) {
      // fallback
      smoothScrollTo(ref.current, { duration: 600 })
    }
  }

  return (
    <>
      <section ref={p1Ref} data-id="p1" className="article__section article__section--one" data-fade>
        <div className="article__content">
          <p>
            From the base of this hill, The Pete seems to breathe in when viewed from afar. With each hit of the sun, the glass reflects the light, and you can clearly see the ribbed metal framework of the building (the skeleton) under the structure's skin. Even before I get close enough to enter The Pete, I can hear and feel the pulse of the footsteps, music, and colliding voices creating a beat-like rhythm. Once inside, The Pete becomes solid, the ground shakes, the air pushes in, and all the energy becomes something tangible.
          </p>
          <div className="article__next"><button className="btn btn--arrow" aria-label="Next paragraph" onClick={() => goNext(p2Ref)}><span className="btn__chev">⌄</span></button></div>
        </div>
      </section>

      <section ref={p2Ref} data-id="p2" className="article__section article__section--two" data-fade>
        <div className="article__content">
          <p>
            The same energy that unifies the masses within The Pete is removed from the space. The coolers that blow air over the people are working overtime to counteract the heat generated by our bodies. The lighting is blindingly bright and makes me think that there is an endless supply of heavy machinery working beneath every single boom and crash. As thousands of people rush in one direction, they take their energy with them, and not just the intangible kind. The Pete is literally a living battery; it transforms emotions into consumption.
          </p>
          <div className="article__next"><button className="btn btn--arrow" aria-label="Next paragraph" onClick={() => goNext(p3Ref)}><span className="btn__chev">⌄</span></button></div>
        </div>
      </section>

      <section ref={p3Ref} data-id="p3" className="article__section article__section--three" data-fade>
        <div className="article__content">
          <p>
            As Lange said, "the first step toward accountability is awareness," and I believe he is correct. If The Pete could tell us how much our happiness costs, perhaps pride isn't the issue; perhaps it is ignorance. If the scoreboard displayed our energy usage rather than our winning points, would our cheers carry more weight, or would it be the same?
          </p>
          <div className="article__next"><button className="btn btn--arrow" aria-label="Next paragraph" onClick={() => goNext(p4Ref)}><span className="btn__chev">⌄</span></button></div>
        </div>
      </section>

      <section ref={p4Ref} data-id="p4" className="article__section article__section--four" data-fade>
        <div className="article__content">
          <p>
            The glow of excess energy from the glass above me illuminates the dark sky as I head back down the hill. But this beauty is not always soft-spoken. The Pete shows us what power is, but quietly asks if we can enjoy that power without losing ourselves.
          </p>
        </div>
      </section>
    </>
  )
}
